baseurl = "https://www.hhyu.org/"
languageCode = "en-us"
Title = "Cortically Magnified"
# Copyright notice. This is displayer in the footer.
copyright = "(c) Hsin-Hao Yu"
theme = "pickles_hhyu"
paginate = 5

[params]
  # Social accounts. Link to these accounts are displayed in the header and
  # footer
  instagram = "hhyu00"
  linkedin = "hsin-hao-yu-165387110"
  github = "hsinhaoyu"
  twitter = "HsinHaoYu"
  # Google Analytics API key.
  ga_api_key = "UA-115187658-1"
  author = "Hsin-Hao Yu"
  authorwebsite = "example.com"
  avatar = "/sitewide/logo.png"
  contact = "mailto:hsinhaohh.yu@gmail.com"
  bio = "A Taiwanese scientist living in Melbourne"
  # Short subtitle/tagline. This is displayed in the header.
  subtitle = "Neuroscience, vision, computation, and other interesting stuff"
  # Logo image. This is displayed ogp image.
  logo = "logo.png"
  favicon = "/path/to/favicon"

  ## specific to this forked version
  micropaginate = 10
  userelated = false

[[menu.main]]
    identifier = "About"
    name       = "/About"
    weight     = 1

[[menu.main]]
    parent     = "About"
    name       = "Me"
    url        = "/about"
    weight     = 1

[[menu.main]]
    parent     = "About"
    name       = "This site"
    url        = "/about_site"
    weight     = 2

[[menu.main]]
    identifier = "Science"
    name       = "/Science"
    weight     = 2

[[menu.main]]
    parent     = "Science"
    name       = "Research"
    url        = "research"
    weight     = 1

[[menu.main]]
    parent     = "Science"
    name       = "CV and Publications"
    url        = "publications"
    weight     = 2

[[menu.main]]
    parent     = "Science"
    name       = "Visualization Gallery"
    url        = "gallery"
    weight     = 3

[[menu.main]]
    identifier = "Update"
    name       = "/Updates"
    weight     = 3

[[menu.main]]
    parent     = "Update"
    name       = "Blog"
    url        = "/"
    weight     = 1

[[menu.main]]
    parent     = "Update"
    name       = "Notes"
    url        = "/micro/"
    weight     = 2

[[menu.main]]
    parent     = "Update"
    name       = "Resources"
    url        = "https://github.com/hsinhaoyu/resources"
    weight     = 3


[[menu.main]]
    name       = "Tags"
    url        = "/tags"
    weight     = 4

[related]
    # Only include matches with rank >= threshold. This is a normalized rank between 0 and 100.
    threshold = 40

    # To get stable "See also" sections we, by default, exclude newer related pages.
    includeNewer = false

    # Will lower case keywords in both queries and in the indexes.
    toLower = false

    [[related.indices]]
    name = "keywords"
    weight = 150
    [[related.indices]]
    name  = "author"
    toLower = true
    weight = 30
    [[related.indices]]
    name  = "tags"
    weight = 100
    [[related.indices]]
    name  = "date"
    weight = 10
    pattern = "2017"
