name: hugo build/deploy
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: clone
        uses: actions/checkout@master
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.79.0'
          # extended: true

      - name: build
        run: hugo --minify

      - name: deploy to AWS S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_DIR: 'public'

      - name: invalidate AWS Cloudfront distribution
        uses: awact/cloudfront-action@master
	env:
	    SOURCE_PATH: 'public'
	    AWS_REGION: ${{ secrets.AWS_REGIONS }}
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
	    DISTRIBITION_ID: ${{ secrets.DISTRIBUTION_ID }}

      - name: notify my slack channel
        uses: rtCamp/action-slack-notify@v2
	env:
	  SLACK_MESSAGE: 'updated Hugo website to AWS'